### PR TITLE
Do not delaycompress in logrotate

### PR DESCRIPTION
**Pull request by CAFxX**
It basically has only downsides when used in combination with copytruncate

See #85

### CODE REVIEW

**Comment by CAFxX** [comment]
Any chance of this going in?

**Comment by cppforlife** [comment]
@CAFxX will be in the upcoming stemcell update.

**Comment by cppforlife** [comment]
@CAFxX i was just chatting with @tylerschultz and there is an interesting point about ease of grepping for recently rotated logs. wdyt about that use case?

**Comment by CAFxX** [comment]
> wdyt about that use case?

I think that `zgrep` is your friend (as it works on both compressed and uncrompressed files) :)

**Comment by tylerschultz** [comment]
@CAFxX ya, DK pointed that out right away. LGTM. Let's please merge into `develop` instead of master.

**Comment by CAFxX** [comment]
Great, thanks!

**Comment by CAFxX** [comment]
@tylerschultz @cppforlife ready for merge to develop

**Pull request merged**
