### PR TITLE
Retry getting agent settings

### PR DESCRIPTION
**Pull request by Kiemes**
Make agent code more resilient, e.g. to handle temporary network issues

[#129348495](https://www.pivotaltracker.com/story/show/129348495)

Signed-off-by: Felix Riegger <felix.riegger@sap.com>

### CODE REVIEW

**Comment by Kiemes** [comment]
In general all units and integration tests are green.

However, we see one integration test failing on our local machine [It labels the raw ephemeral paths for unpartitioned disks](https://github.com/cloudfoundry/bosh-agent/blob/257a51094b68933f3e26a65e561c6c49cdb9b6a2/integration/raw_ephemeral_disk_test.go#L86). This one was failing already before we introduced our changes. On the pipeline this [commit](https://main.bosh-ci.cf-app.com/pipelines/bosh-agent/jobs/test-integration/builds/298) runs green. Any idea why this could be failing in our case? Maybe a Mac thing?

**Comment by dpb587-pivotal** [comment]
Story to investigate the flaky/failing raw ephemeral paths test: https://www.pivotaltracker.com/story/show/130333367

**Comment by dpb587-pivotal** [comment]
Merge story: https://www.pivotaltracker.com/story/show/132002823

**Comment by friegger** [comment]
Thanks @dpb587-pivotal !

**Pull request merged**
