### PR TITLE
Partioning a root disk respects configured swap_size

### PR DESCRIPTION
**Pull request by KaiHofstetter**
[#150754334](https://www.pivotaltracker.com/story/show/150754334)

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Merge Story: https://www.pivotaltracker.com/story/show/151530471

**Comment by GarfieldIsAPhilosopher** [comment]
Hi @KaiHofstetter we tried to package a gcp stemcell with this new agent, during deployment the agent is unresponsive, wonder if you have run into similar issues, thanks

**Comment by voelzmo** [comment]
Hey Difan,

we didn’t have a GCP env available, so we didn’t test there. What agent behavior are you observing? Does the agent log contain anything useful regarding partitioning or the unresponsiveness you experience?

**Comment by GarfieldIsAPhilosopher** [comment]
The deployment failed because of time out trying to connect to the compilation vm(unresponsive agent), since the agent is unresponsive, we could not get logs out

**Comment by zachgersh** [comment]
@voelzmo - I think we had misconfigured the previously deployment. I built a new dev-stemcell with your agent code and it worked on a clean deploy and then I configured `swap_size` to zero on GCP and got

screen shot 2017-10-11 at 5 12 14 pm

will go ahead and merge this tomorrow when I am back in the office.

**Pull request merged**
