### PR TITLE
add useful testing script to quickly update stemcells with local agent binary

### PR DESCRIPTION
**Pull request by cppforlife**
cc @pivotal-jamil-shamy @tylerschultz @dpb587-pivotal

### CODE REVIEW

**Comment by tylerschultz** [comment]
This looks fantastic.

Should this task folder be called something else? It's not actually building a stemcell, it's re-packing it with a modified agent.

**Comment by cunnie** [comment]
@tylerschultz good point, I'll change the directory: `build-stemcell` &rarr; `repack-stemcell-with-new-agent` and re-submit PR (if that's okay with you, @cppforlife )

**Comment by cppforlife** [comment]
@cunnie how about `repack-stemcell` to be concise.

**Comment by cunnie** [comment]
@tylerschultz : directory (and documentation) have been modified to convey that we are _repacking_ an existing stemcell rather than _building_ a new stemcell. Merge at your convenience.

**Pull request merged**
