### PR TITLE
Setup /var/log/lastlog

### PR DESCRIPTION
**Pull request by aduffeck**
/var/log/lastlog is not written in openSUSE if it doesn't already exist.

### CODE REVIEW

**Comment by cppforlife** [comment]
@aduffeck would you mind adding unit tests that assert that these command are called.

**Comment by cppforlife** [comment]
@aduffeck brain fart from my side... can you switch to using fs's Chown/Chmod [1] and WriteFileString [2]

[1] https://github.com/cloudfoundry/bosh-utils/blob/87d3668a74af6d395aae97a3764aac279abbaf42/system/file_system_interface.go#L28-L29
[2] https://github.com/cloudfoundry/bosh-utils/blob/87d3668a74af6d395aae97a3764aac279abbaf42/system/file_system_interface.go#L33

**Comment by cppforlife** [comment]
prioritized to pull in: https://www.pivotaltracker.com/story/show/157071295

**Comment by christarazi** [comment]
Closing due to inactivity. Feel free to open again if you want to.

**Pull request closed without merging**
