### PR TITLE
[WIP] Support for Softlayer network (code review)

### PR DESCRIPTION
**Pull request by gu-bin**
In Softlayer if /etc/network/interfaces is modified, user can't access the VM any more. So for softlayer we only need to modify /etc/resolv.conf to write DNS information got from network settings and must keep /etc/network/interfaces unchanged.

We'd like to use a new network type "softlayer" (or change to another name) in deployment yml. In order to make bosh director pass the manifest parser, the bosh director code cloud_manifest_parser.rb also needs to modify (add when 'softlayer') to support the new type "softlayer":
```ruby
          case type
            when 'manual'
              network = ManualNetwork.new(@deployment, network_spec)
            when 'dynamic'
              network = DynamicNetwork.new(@deployment, network_spec)
            when 'vip'
              network = VipNetwork.new(@deployment, network_spec)
            else
              raise DeploymentInvalidNetworkType,
                "Invalid network type `#{type}'"
          end
```

### CODE REVIEW

**Comment by cppforlife** [comment]
Im not sure I understand how the networking will be configured then if agent does not do it. I know that previous versions of softlayer CPI configured networking by SSH-ing from the CPI into the agents, but that's something we need to eliminate as it's not good idea for the CPI to SSH into all VMs.

**Comment by gu-bin** [comment]
In Softlayer, only /etc/resolv.conf needs to be modified to configure DNS. It's done by bosh agent and that's all for network configuration. The existing /etc/network/interfaces is used and can't be changed, or the vm can't be accessed. The Softlayer CPI doesn't configure network by any means.

**Comment by bosh-ci-push-pull** [comment]
Something configures /etc/network/interfaces in ubuntu for example. What's in that file and what writes it out.

**Comment by maximilien** [comment]
@gu-bin please respond to @bosh-ci-push-pull as it's a proxy account for @cppforlife and others in the BOSH team. Thanks,

max

**Comment by maximilien** [comment]
@gu-bin also, where are the tests?

**Comment by gu-bin** [comment]
@maximilien @bosh-ci-push-pull 

As I'm not sure if this approach will be accepted by community, just send 
out the PR #30 for your code review. No unit test code for now as it needs 
some effort. If the community agree to accept our code, I will add the 
unit test.


Best Regards,

Bin Gu (顾彬)

Bluemix, IBM China Software Development Lab
Tel: (8610)82454944
Email: gubin@cn.ibm.com
Address: 3F, Ring Bldg, ZhongGuanCun Software Park No.28, Dongbeiwang West 
Road No.8,ShangDi, Haidian District,Beijing 100193, PRC

**Comment by gu-bin** [comment]
@bosh-ci-push-pull /etc/network/interfaces is written by Softlayer. We just use it and don't change it. Softlayer assign an IP to each vm and write the information to /etc/network/interfaces.

**Comment by gu-bin** [comment]
@bosh-ci-push-pull 
This is a sample of /etc/network/interfaces in Softlayer:

cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

auto lo
# The loopback network interface
iface lo inet loopback

# eth0
auto eth0
allow-hotplug eth0
iface eth0 inet static
	address 10.40.236.76
	netmask 255.255.255.192
	post-up route add -net 10.0.0.0 netmask 255.0.0.0 gw 10.40.236.65

# eth1
auto eth1
allow-hotplug eth1
iface eth1 inet static
	address 184.172.3.90
	netmask 255.255.255.240
	gateway 184.172.3.81

**Comment by gu-bin** [comment]
Closing this one. #35 is the new PR.

**Pull request closed without merging**
