### PR TITLE
Add support for openSUSE Leap 42.2 stemcells

### PR DESCRIPTION
**Pull request by aduffeck**
This pull request makes the bosh-agent compatible with openSUSE by adapting the network and certificate management accordingly.

It is a dependency of the openSUSE stemcell pull request[1].

[1] https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/4

### CODE REVIEW

**Comment by cppforlife** [comment]
story: https://www.pivotaltracker.com/story/show/146464235

**Comment by tjvman** [comment]
This doesn't compile when merged on top the head of master because the NetManager interface requires a `SetupIPv6` method. You don't have to provide a working implementation unless you want to; CentOSNetManager just returns `nil`.

**Comment by jimmykarily** [comment]
Rebased to upstream/master and added a "nil" implementation of SetupIPv6 method

**Comment by monkeyherder** [comment]
Manually pulled in

**Comment by pburkholder** [comment]
Hi @aduffeck -- Could you venture a guess how many person-hours it took you to add a stemcell? More than 1000? More than 2000 hours (a person-year of time)?  Thanks! --Peter

**Pull request closed without merging**
